### ISSUE TITLE
I cannot understand these commands, how to use them to find my save's seed successfully?

### ISSUE THREAD

**Issue by ysysj1234** [crackedMagnet/SeedFinderMod#10]
I have a save and I cannot get its seed, the positions of the structures are:
1st village XZ:4484 5556
2nd village XZ:2773 4492
3rd village XZ:203 1675
4th village XZ:-5045 1227
5th village XZ:-2043 4372
6th village XZ:-3510 2541
7th village XZ:4580 4132
1st ruined portal XZ:-4203 2596
2nd ruined portal XZ:4739 3291
How can I enter command/findseed to find my save's seed correctly?

**Comment by crackedMagnet** [comment]
I think you miss understand what this mod is for.  It finds a seed for a new world you want to create.  It does not find the seeds of existing worlds, thats reverse seed finding or seed cracking.  If you have a save as you say you do, you can just type /seed to get the seed.
