### ISSUE TITLE
Please update to version 1.20.1

### ISSUE THREAD

**Issue by Walkersifolia** [crackedMagnet/SeedFinderMod#6]

**Comment by crackedMagnet** [comment]
Do you know of any open source 1.20 compatible mods that add a custom world type to the create world screen?  They have changed the way it works and I'm having trouble working out how to do it.  An example would help a lot.

**Comment by Walkersifolia** [comment]
> Do you know of any open source 1.20 compatible mods that add a custom world type to the create world screen? They have changed the way it works and I'm having trouble working out how to do it. An example would help a lot.

OK, I will pay attention on it, if I have any news, how should I inform you as soon as possible. How can I contact you? Just on GitHub or other way?

**Comment by crackedMagnet** [comment]
It's all good, I've found one.  I've had to completely rework the way it detects the world type.  I should have a 1.20.1 version out in 3 or 4 days time.  There is still some work to be done with the bedrock structures as they aren't spawning when using next_bedrock.

**Comment by Walkersifolia** [comment]
> It's all good, I've found one. I've had to completely rework the way it detects the world type. I should have a 1.20.1 version out in 3 or 4 days time. There is still some work to be done with the bedrock structures as they aren't spawning when using next_bedrock.

Amazing! Congratulations on this discovery. I will expect it

**Comment by Walkersifolia** [comment]
How can I use this mod in a muliplayer server? I need to crack seed in a server.

**Comment by crackedMagnet** [comment]
This mod finds seeds for a new world.  It doesn't crack seeds of existing worlds/servers.  Thats reverse seed finding or seed cracking.

**Comment by Walkersifolia** [comment]
Hum...do you know of any way to crack the seed? I really need it.

**Comment by crackedMagnet** [comment]
It's not what I do.  If the server owner doesn't want to give you the seed, its probably because they don't people having an unfair advantage over others.

**Comment by Walkersifolia** [comment]
It's not about gaining an advantage over other players. The server owner is me, I just want to test any way to cheat and try to banned.

**Comment by crackedMagnet** [comment]
If you are the server owner then just type /seed and it will give you the seed.

**Comment by Walkersifolia** [comment]
I know it, I mean is I put myself in the role of an ordinary player. I am testing how ordinary players get seeds by cheating. I want to prevent this behavior, such as changing seeds regularly and deleting chunks.

**Comment by Walkersifolia** [comment]
Thank you so much

**Comment by crackedMagnet** [comment]
If you want to prevent people from cheating by reversing the seed, see if you can find a mod that changes all the salt/hash values for the structures and ores.  Then even if they manage to get the seed nothing will be where chunk base says it is.

**Comment by Walkersifolia** [comment]
> If you want to prevent people from cheating by reversing the seed, see if you can find a mod that changes all the salt/hash values for the structures and ores. Then even if they manage to get the seed nothing will be where chunk base says it is.

Very thank you! I will try it right now!
